pipeline {
    agent any

    stages {

        stage('Check Docker') {
            steps {
                bat 'docker version'
                bat 'docker ps'
            }
        }

        stage('Build Docker Image') {
            steps {
                bat 'docker build -t my-nginx-app .'
            }
        }

        stage('Run Container') {
            steps {
                bat '''
                docker stop my-nginx-container
                docker rm my-nginx-container
                docker run -d --name my-nginx-container -p 8080:80 my-nginx-app
                '''
            }
        }

    }
}
