pipeline {
    agent any

    stages {

        stage('Build Docker Image') {
            steps {
                dir('jenkins-docker-demo') {
                    bat 'docker build -t my-nginx-app .'
                }
            }
        }

        stage('Run Container') {
            steps {
                bat '''
                docker stop my-nginx-container >nul 2>&1
                docker rm my-nginx-container >nul 2>&1
                docker run -d --name my-nginx-container -p 8080:80 my-nginx-app
                '''
            }
        }

    }
}
